// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg3Xp_xgG3Zh_2-XdExJQsU_aONiFXCCY',
    appId: '1:1033143975541:web:b7db4a192d4f8f9387823c',
    messagingSenderId: '1033143975541',
    projectId: 'reviews-waves-86c01',
    authDomain: 'reviews-waves-86c01.firebaseapp.com',
    storageBucket: 'reviews-waves-86c01.firebasestorage.app',
    measurementId: 'G-4YNGJVE82E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHLJut2pZd38siLJoq-LmJpoz3ydSZsN8',
    appId: '1:1033143975541:android:af93bf04ea5ef8b687823c',
    messagingSenderId: '1033143975541',
    projectId: 'reviews-waves-86c01',
    storageBucket: 'reviews-waves-86c01.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg3Xp_xgG3Zh_2-XdExJQsU_aONiFXCCY',
    appId: '1:1033143975541:web:47a45c69629c43c887823c',
    messagingSenderId: '1033143975541',
    projectId: 'reviews-waves-86c01',
    authDomain: 'reviews-waves-86c01.firebaseapp.com',
    storageBucket: 'reviews-waves-86c01.firebasestorage.app',
    measurementId: 'G-Y4VE6W8M1X',
  );
}
